### ISSUE TITLE
Add simple example of importing .graphql files

### ISSUE THREAD

**Issue by Fconstant** [bamlab/react-native-graphql-transformer#1]
It was not clear to me how can I use this transformer with other packages inside RN, like `graphql` or `apollo-client`.

**Comment by yordis** [comment]
```graphql
# my-query.graphql

query GetName {
  name
}
```

```js
// my-js-file.js
import GetName from "./my-query"

// apollo client
client.query({
  query: GetName
})
```

**Comment by Fconstant** [comment]
Awesome.
Maybe a PR with this simple example at the docs could benefit other users.
I'll be creating this PR in the next few days
