### ISSUE TITLE
update for RN 56?

### ISSUE THREAD

**Issue by arolson101** [bamlab/react-native-graphql-transformer#2]
react-native-typescript-transformer has been updated to handle RN >= 56; could you do the same?  I'm currently getting ```Cannot find module 'metro/src/transformer'```

```ts
if (reactNativeMinorVersion >= 56) {
  upstreamTransformer = require('metro/src/reactNativeTransformer')
} else if (reactNativeMinorVersion >= 52) {
  upstreamTransformer = require('metro/src/transformer')
} else if (reactNativeMinorVersion >= 47) {
  upstreamTransformer = require('metro-bundler/src/transformer')
} else if (reactNativeMinorVersion === 46) {
  upstreamTransformer = require('metro-bundler/build/transformer')
```

**Comment by tpucci** [comment]
Good morning, thank you for this example ! We have updated the repo :)
You have been added to the contributors 🎉

**Comment by tychota** [comment]
Well done @arolson101 and sorry for big leadtime between the issue and the reaction.
